apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonappsimple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonappsimple
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: pythonappsimple
    spec:
      containers:
      - name: pythonappsimple_container
        image: gcr.io/website-gcp-terra/pythonappsimpleimage
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m